wipe = true
no-hooks = true
no-tests = true
no-rows-affected = true

[psql]
dbname = "avakian"
host = "localhost"
port = 5431
user = "avakian"
pass = "avakian"
sslmode = "disable"
blacklist = ["schema_migrations"]