version: "3"

services:
    avakian:
        build:
            context: .
        container_name: avakian
        depends_on: 
            - pg
        env_file: prod-test.env
        restart: unless-stopped
        networks:
            - avakian
    pg:
        image: postgres
        container_name: avakian-pg
        env_file: db.env
        restart: unless-stopped
        volumes:
            - /var/srv/avakian/db:/var/lib/postgresql/data
        ports:
            - "5432"
        networks:
            - avakian

networks:
    avakian:
        external: true