// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Prefix is an object representing the database table.
type Prefix struct {
	ID             int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	GuildSnowflake string    `boil:"guild_snowflake" json:"guild_snowflake" toml:"guild_snowflake" yaml:"guild_snowflake"`
	Prefix         string    `boil:"prefix" json:"prefix" toml:"prefix" yaml:"prefix"`
	CreatedAt      time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt      time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *prefixR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L prefixL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PrefixColumns = struct {
	ID             string
	GuildSnowflake string
	Prefix         string
	CreatedAt      string
	UpdatedAt      string
}{
	ID:             "id",
	GuildSnowflake: "guild_snowflake",
	Prefix:         "prefix",
	CreatedAt:      "created_at",
	UpdatedAt:      "updated_at",
}

var PrefixTableColumns = struct {
	ID             string
	GuildSnowflake string
	Prefix         string
	CreatedAt      string
	UpdatedAt      string
}{
	ID:             "prefixes.id",
	GuildSnowflake: "prefixes.guild_snowflake",
	Prefix:         "prefixes.prefix",
	CreatedAt:      "prefixes.created_at",
	UpdatedAt:      "prefixes.updated_at",
}

// Generated where

var PrefixWhere = struct {
	ID             whereHelperint64
	GuildSnowflake whereHelperstring
	Prefix         whereHelperstring
	CreatedAt      whereHelpertime_Time
	UpdatedAt      whereHelpertime_Time
}{
	ID:             whereHelperint64{field: "\"prefixes\".\"id\""},
	GuildSnowflake: whereHelperstring{field: "\"prefixes\".\"guild_snowflake\""},
	Prefix:         whereHelperstring{field: "\"prefixes\".\"prefix\""},
	CreatedAt:      whereHelpertime_Time{field: "\"prefixes\".\"created_at\""},
	UpdatedAt:      whereHelpertime_Time{field: "\"prefixes\".\"updated_at\""},
}

// PrefixRels is where relationship names are stored.
var PrefixRels = struct {
	GuildSnowflakeGuild string
}{
	GuildSnowflakeGuild: "GuildSnowflakeGuild",
}

// prefixR is where relationships are stored.
type prefixR struct {
	GuildSnowflakeGuild *Guild `boil:"GuildSnowflakeGuild" json:"GuildSnowflakeGuild" toml:"GuildSnowflakeGuild" yaml:"GuildSnowflakeGuild"`
}

// NewStruct creates a new relationship struct
func (*prefixR) NewStruct() *prefixR {
	return &prefixR{}
}

// prefixL is where Load methods for each relationship are stored.
type prefixL struct{}

var (
	prefixAllColumns            = []string{"id", "guild_snowflake", "prefix", "created_at", "updated_at"}
	prefixColumnsWithoutDefault = []string{"guild_snowflake", "prefix"}
	prefixColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	prefixPrimaryKeyColumns     = []string{"id"}
)

type (
	// PrefixSlice is an alias for a slice of pointers to Prefix.
	// This should almost always be used instead of []Prefix.
	PrefixSlice []*Prefix

	prefixQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	prefixType                 = reflect.TypeOf(&Prefix{})
	prefixMapping              = queries.MakeStructMapping(prefixType)
	prefixPrimaryKeyMapping, _ = queries.BindMapping(prefixType, prefixMapping, prefixPrimaryKeyColumns)
	prefixInsertCacheMut       sync.RWMutex
	prefixInsertCache          = make(map[string]insertCache)
	prefixUpdateCacheMut       sync.RWMutex
	prefixUpdateCache          = make(map[string]updateCache)
	prefixUpsertCacheMut       sync.RWMutex
	prefixUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single prefix record from the query.
func (q prefixQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Prefix, error) {
	o := &Prefix{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for prefixes")
	}

	return o, nil
}

// All returns all Prefix records from the query.
func (q prefixQuery) All(ctx context.Context, exec boil.ContextExecutor) (PrefixSlice, error) {
	var o []*Prefix

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Prefix slice")
	}

	return o, nil
}

// Count returns the count of all Prefix records in the query.
func (q prefixQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count prefixes rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q prefixQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if prefixes exists")
	}

	return count > 0, nil
}

// GuildSnowflakeGuild pointed to by the foreign key.
func (o *Prefix) GuildSnowflakeGuild(mods ...qm.QueryMod) guildQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"guild_snowflake\" = ?", o.GuildSnowflake),
	}

	queryMods = append(queryMods, mods...)

	query := Guilds(queryMods...)
	queries.SetFrom(query.Query, "\"guilds\"")

	return query
}

// LoadGuildSnowflakeGuild allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (prefixL) LoadGuildSnowflakeGuild(ctx context.Context, e boil.ContextExecutor, singular bool, maybePrefix interface{}, mods queries.Applicator) error {
	var slice []*Prefix
	var object *Prefix

	if singular {
		object = maybePrefix.(*Prefix)
	} else {
		slice = *maybePrefix.(*[]*Prefix)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &prefixR{}
		}
		args = append(args, object.GuildSnowflake)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &prefixR{}
			}

			for _, a := range args {
				if a == obj.GuildSnowflake {
					continue Outer
				}
			}

			args = append(args, obj.GuildSnowflake)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`guilds`),
		qm.WhereIn(`guilds.guild_snowflake in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Guild")
	}

	var resultSlice []*Guild
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Guild")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for guilds")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for guilds")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.GuildSnowflakeGuild = foreign
		if foreign.R == nil {
			foreign.R = &guildR{}
		}
		foreign.R.GuildSnowflakePrefix = object
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.GuildSnowflake == foreign.GuildSnowflake {
				local.R.GuildSnowflakeGuild = foreign
				if foreign.R == nil {
					foreign.R = &guildR{}
				}
				foreign.R.GuildSnowflakePrefix = local
				break
			}
		}
	}

	return nil
}

// SetGuildSnowflakeGuild of the prefix to the related item.
// Sets o.R.GuildSnowflakeGuild to related.
// Adds o to related.R.GuildSnowflakePrefix.
func (o *Prefix) SetGuildSnowflakeGuild(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Guild) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"prefixes\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"guild_snowflake"}),
		strmangle.WhereClause("\"", "\"", 2, prefixPrimaryKeyColumns),
	)
	values := []interface{}{related.GuildSnowflake, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.GuildSnowflake = related.GuildSnowflake
	if o.R == nil {
		o.R = &prefixR{
			GuildSnowflakeGuild: related,
		}
	} else {
		o.R.GuildSnowflakeGuild = related
	}

	if related.R == nil {
		related.R = &guildR{
			GuildSnowflakePrefix: o,
		}
	} else {
		related.R.GuildSnowflakePrefix = o
	}

	return nil
}

// Prefixes retrieves all the records using an executor.
func Prefixes(mods ...qm.QueryMod) prefixQuery {
	mods = append(mods, qm.From("\"prefixes\""))
	return prefixQuery{NewQuery(mods...)}
}

// FindPrefix retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPrefix(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*Prefix, error) {
	prefixObj := &Prefix{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"prefixes\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, prefixObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from prefixes")
	}

	return prefixObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Prefix) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no prefixes provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(prefixColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	prefixInsertCacheMut.RLock()
	cache, cached := prefixInsertCache[key]
	prefixInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			prefixAllColumns,
			prefixColumnsWithDefault,
			prefixColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(prefixType, prefixMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(prefixType, prefixMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"prefixes\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"prefixes\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into prefixes")
	}

	if !cached {
		prefixInsertCacheMut.Lock()
		prefixInsertCache[key] = cache
		prefixInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the Prefix.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Prefix) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	key := makeCacheKey(columns, nil)
	prefixUpdateCacheMut.RLock()
	cache, cached := prefixUpdateCache[key]
	prefixUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			prefixAllColumns,
			prefixPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return errors.New("models: unable to update prefixes, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"prefixes\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, prefixPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(prefixType, prefixMapping, append(wl, prefixPrimaryKeyColumns...))
		if err != nil {
			return err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	_, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update prefixes row")
	}

	if !cached {
		prefixUpdateCacheMut.Lock()
		prefixUpdateCache[key] = cache
		prefixUpdateCacheMut.Unlock()
	}

	return nil
}

// UpdateAll updates all rows with the specified column values.
func (q prefixQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) error {
	queries.SetUpdate(q.Query, cols)

	_, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all for prefixes")
	}

	return nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PrefixSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) error {
	ln := int64(len(o))
	if ln == 0 {
		return nil
	}

	if len(cols) == 0 {
		return errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), prefixPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"prefixes\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, prefixPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	_, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to update all in prefix slice")
	}

	return nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Prefix) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no prefixes provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	nzDefaults := queries.NonZeroDefaultSet(prefixColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	prefixUpsertCacheMut.RLock()
	cache, cached := prefixUpsertCache[key]
	prefixUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			prefixAllColumns,
			prefixColumnsWithDefault,
			prefixColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			prefixAllColumns,
			prefixPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert prefixes, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(prefixPrimaryKeyColumns))
			copy(conflict, prefixPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"prefixes\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(prefixType, prefixMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(prefixType, prefixMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert prefixes")
	}

	if !cached {
		prefixUpsertCacheMut.Lock()
		prefixUpsertCache[key] = cache
		prefixUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single Prefix record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Prefix) Delete(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil {
		return errors.New("models: no Prefix provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), prefixPrimaryKeyMapping)
	sql := "DELETE FROM \"prefixes\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	_, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete from prefixes")
	}

	return nil
}

// DeleteAll deletes all matching rows.
func (q prefixQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) error {
	if q.Query == nil {
		return errors.New("models: no prefixQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	_, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from prefixes")
	}

	return nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PrefixSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) error {
	if len(o) == 0 {
		return nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), prefixPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"prefixes\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, prefixPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	_, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return errors.Wrap(err, "models: unable to delete all from prefix slice")
	}

	return nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Prefix) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPrefix(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PrefixSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PrefixSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), prefixPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"prefixes\".* FROM \"prefixes\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, prefixPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in PrefixSlice")
	}

	*o = slice

	return nil
}

// PrefixExists checks if the Prefix row exists.
func PrefixExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"prefixes\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if prefixes exists")
	}

	return exists, nil
}
