BEGIN;

CREATE TABLE quotes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    idx int NOT NULL,

    quoter_snowflake text NOT NULL,
    author_snowflake text NOT NULL,

    message_snowflake text NOT NULL UNIQUE,
    channel_snowflake text NOT NULL,
    guild_snowflake text NOT NULL,

    created_at timestamp NOT NULL DEFAULT NOW(),
    updated_at timestamp NOT NULL DEFAULT NOW(),

    UNIQUE(guild_snowflake, idx)
);

ALTER TABLE guilds ADD COLUMN do_quotes boolean DEFAULT 'false' NOT NULL;

COMMIT;